name: Test
on:
  push: {}
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install libraries
        run: sudo apt-get update && sudo apt-get install -y libpam0g-dev

      - name: Test
        run: make test
